---
title: "Academic activities"
---

# Invited Lectures

## 2023

1.  **Presentation Title:** Anatomy of spine
    -   **Conference:** The 3rd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2023
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Date:** September 9, 2023
2.  **Presentation Title:** US Findings of The Elbow with Live Demonstration
    -   **Conference:** The 2nd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2023
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Date:** July 15, 2023
3.  **Presentation Title:** Manipulation
    -   **Conference:** The Summer Continuing Education Course of The Korean Academy of Rehabilitation Medicine
    -   **Organizing institution:** The Korean Academy of Rehabilitation Medicine
    -   **Date:** June 11, 2023
4.  **Presentation Title:** Self-Exercise Therapy Methods for Rheumatic Diseases
    -   **Conference:** The 2023 March Continuing Education Course of The Korean College of Rheumatology
    -   **Organizing institution:** Korean College of Rheumatology
    -   **Date:** March 25, 2023
5.  **Presentation Title:** "How are extra-articular pathologies of The Hip joint diagnosed and treated?"
    -   **Conference:** Korean Association of Pain Medicine Spring Academic Conference 2023
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** March 18, 2023

## 2022

1.  **Presentation Title:** Overview of osteoarthritis & Rheumatic diseases
    -   **Conference:** Korean Association of Pain Medicine Review Course 2022
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** December 3, 2022
2.  **Presentation Title:** Cross-sectional Anatomy and Ultrasonographic Live Demo of Leg, Foot, and Ankle
    -   **Conference:** Korean Academy of Neuro-Musculoskeletal Sonography Autumn Academic Conference 2022
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Date:** November 5, 2022
3.  **Presentation Title:** Anatomy of spine
    -   **Conference:** The 3rd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2022
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Date:** September 3, 2022
4.  **Presentation Title:** Common Spine Disorders and Medical Treatments in The Elderly
    -   **Conference:** Korean Society of ProsThetics and Orthotics Spring Academic Conference 2022
    -   **Organizing institution:** Korean Society of ProsThetics and Orthotics
    -   **Date:** May 28, 2022
5.  **Presentation Title:** Anatomy of Hip & Knee
    -   **Conference:** The 1st Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2022
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Date:** April 30, 2022
6.  **Presentation Title:** "How should small or medium-sized rotator cuff tears be treated?"
    -   **Conference:** Korean Association of Pain Medicine Spring Academic Conference 2022
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** March 26, 2022
7.  **Presentation Title:** Anatomy of Hip & Knee
    -   **Conference:** The 2nd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2021
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Date:** January 15, 2022

## \~ 2021

8.  **Presentation Title:** Common Cervical Spine Disorder
    -   **Conference:** Korean Association of Pain Medicine Online Review Course 2021
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** December 4, 2021
9.  **Presentation Title:** Pathophysiology and Clinical Assessment of Radiculopathy
    -   **Conference:** Korean Association of Pain Medicine Spring Academic Conference 2021
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** March 27, 2021
10. **Presentation Title:** Overview of osteoarthritis & Rheumatic diseases
    -   **Conference:** Korean Association of Pain Medicine Online Review Course 2020
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** December 5, 2020
11. **Presentation Title:** Pathophysiology and Clinical Manifestations of Neuropathic Cancer Pain
    -   **Conference:** Korean Association of Pain Medicine Autumn Academic Conference 2020
    -   **Organizing institution:** Korean Association of Pain Medicine
    -   **Date:** November 14, 2020

## Branches and Regional Gathering

1.  **Presentation Title:** The Utility of InBody in The Diagnosis of Sarcopenia
    -   **Conference:** The 150th Meeting of The Korean Academy of Rehabilitation Medicine, Busan-Ulsan-Gyeongnam Region
    -   **Organizing institution:** The Korean Academy of Rehabilitation Medicine, Busan-Ulsan-Gyeongnam Region
    -   **Date:** November 25, 2021
2.  **Presentation Title:** Comparison of US and C-arm Guided Spinal Injection: Cons and Pros
    -   **Conference:** The 148th Meeting of The Korean Academy of Rehabilitation Medicine, Busan-Ulsan-Gyeongnam Region
    -   **Organizing institution:** The Korean Academy of Rehabilitation Medicine, Busan-Ulsan-Gyeongnam Region
    -   **Date:** July 15, 2021
3.  **Presentation Title:** PharmacoTherapy in Cognitive Rehabilitation after TBI
    -   **Conference:** The 146th Meeting of The Korean Academy of Rehabilitation Medicine, Busan-Ulsan-Gyeongnam Region
    -   **Organizing institution:** The Korean Academy of Rehabilitation Medicine, Busan-Ulsan-Gyeongnam Region
    -   **Date:** November 28, 2019

# Professional Memberships

-   Korean Medical Association
    -   Member (2010-present)
    -   Central Director (2017-2018)
    -   Representative Assembly (2017-2018)
-   Korean Association of Public Health Doctors
    -   Member (2015-2018)
    -   Vice President (2017-2018)
    -   Advisor (2018-2019)
-   Korean Academy of Rehabilitation Medicine
    -   Member (2011-present)
    -   Clinical Practice Guideline Committee Member (2022-2024)
-   Korean Association of Pain Medicine
    -   Member (2018-present)
    -   Academic Committee Member (2019-present)
-   The Korean Society of Sports Medicine
    -   Member (2018-present)
-   Korean Academy of Neuro-Musculoskeletal Sonography
    -   Member (2018-present)
    -   Education Committee Member (2022-present)
-   Korean Society of Artificial Intelligence in Medicine
    -   Member (2019-present)
-   The Korean Pain Research Society
    -   Member (2022-present)
    -   Planning Committee Member (2022-present)
-   International Society of Physical & Rehabilitation Medicine
    -   Member (2022-present)

# Review

-   The 51st Annual Meeting and International Conference of The Korean Academy of Rehabilitation Medicine (KARM 2023)
-   Annals of Rehabilitation Medicine : 2023 - present

# Education

## University

-   **Course**: Student Internship Program in Rehabilitation Medicine
    -   **Academic Year**: 2022-2023
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Supervising Professor
-   **Course**: Clinical Practicum in Rehabilitation Medicine
    -   **Academic Year**: 2020-2023
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: **Course** Coordinator(2022-) and Lecturer
-   **Course**: CPX Internal Special Lecture
    -   **Academic Year**: 2020-2023
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Evaluator and Lecturer
-   **Course**: Musculoskeletal system
    -   **Title**: Musculoskeletal rehabilitation
    -   **Academic Year**: 2020-2023
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Lecturer
-   **Course**: Respiratory Medicine
    -   **Title**: Pulmonary rehabilitation
    -   **Academic Year**: 2020-2023
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Lecturer
-   **Course**: Neuroscience
    -   **Title**: Pain & pain pathway
    -   **Academic Year**: 2020-2023
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Lecturer
-   **Course**: Growth and Aging
    -   **Title**: Geriatric Musculoskeletal Disorders
    -   **Academic Year**: 2020-2022
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Lecturer
-   **Course**: Medical Informatics in rehabilitative medicine
    -   **Title**: Medical Informatics
    -   **Academic Year**: 2020-2022
    -   **Institution**: Kosin University College of Medicine
    -   **Role**: Lecturer
-   **Course**: Graduate School of Public Health
    -   **Title**: Disease Control in The Field of Musculoskeletal Rehabilitation
    -   **Academic Year**: 2019-2020
    -   **Institution**: Kosin University Graduate School of Public Health
    -   **Role**: Lecturer

## Academic workshop

-   **Course** Ultrasound Practicum of The Peripheral Nerve and Spine
    -   **Title** The 3rd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2023
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Role**: Practicum Instructor
    -   **Date** September 9, 2023
-   **Course** Ultrasound Practicum of The Shoulder, Elbow, Wrist and Hand
    -   **Title** The 2nd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2023
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Role**: Practicum Instructor
    -   **Date** June 30, 2023
-   **Course** Ultrasound Practicum of The Lumbar Spine and Peripheral Nerve of The Upper and Lower Extremity
    -   **Title** The 3rd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2022
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Role**: Practicum Instructor
    -   **Date** September 3, 2022
-   **Course** Ultrasound Practicum of The Hip, Ankle and Foot
    -   **Title:** The 1st Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2022
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Role**: Practicum Instructor
    -   **Date:** April 30, 2022
-   **Course** 1. Ultrasound Practicum of The Hip, Knee, Ankle and Foot, 2. Ultrasound Practicum of The Lumbar Spine and Peripheral Nerve of The Lower Extremity
    -   **Title** The 2nd Hands-on Workshop of The Korean Academy of Neuro-Musculoskeletal Sonography 2021
    -   **Organizing institution:** Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Role**: Practicum Instructor
    -   **Date** January 15, 2022
-   **Course** Upper Extremity Ultrasound: Theory, Live Scan, and Hands-on
    -   **Title** Collaborative Ultrasound Hands-on Seminar in Busan of The Korean Academy of Neuro-Musculoskeletal Sonography
    -   **Organizing institution:** Samsung Medicine Co., Ltd.
    -   **Role**: Practicum Instructor
    -   **Date** November 27, 2021

# AWARDS

1.  **AWARD: Best oral presentation**
    -   **Title**: "Pressure Characteristics of The Knee Joints"
    -   **conference**: 2019 Korean Academy of Neuro-Musculoskeletal Sonography Spring Academic Conference

# Media

1.  **Title:** 'KNN 건강365' 어깨 통증에 응급실? 원인은 돌가루
    -   **Date:** January 24, 2022 https://news.knn.co.kr/news/article/123830
2.  **Title:** 'KNN 건강365' 목 디스크, 턱 당기는 자세 금물!
    -   **Date:** January 17, 2022 https://news.knn.co.kr/news/article/123621
3.  **Title:** '기독교보' 복음병원 명의를 만나다
    -   **Date:** November 24, 2021 http://www.kosinnews.com/news/articleView.html?idxno=22910
4.  **Title:** '부산mbc라디오 생방송 오늘 저녁, 부산입니다.'
    -   **Date:** November 2, 2021
5.  **Title:** 'KNN 웰빙라이프'
    -   **Date:** October 12-17, 2020
6.  **Title:** 'KNN 공개클리닉 웰' 100세 건강 만성질환 관리가 답이다
    -   **Date:** December 23, 2029 https://www.knn.co.kr/tv/well/vods/103/101727
