# Academic Activities

## Invited Lectures

### 2022

1.  **Title:** "2022 Review Course of the Korean Society of Clinical Pain Medicine"
    -   **Conference:** Korean Society of Clinical Pain Medicine
    -   **Date:** December 3, 2022
2.  **Title:** "2022 Autumn Academic Conference of the Korean Society of Neuromusculoskeletal Ultrasonography"
    -   **Conference:** Korean Society of Neuromusculoskeletal Ultrasonography
    -   **Date:** November 5, 2022
3.  **Title:** "The 3rd Hands-on Workshop of the Korean Society of Neuromusculoskeletal Ultrasonography 2022"
    -   **Conference:** Korean Society of Neuromusculoskeletal Ultrasonography
    -   **Date:** September 3, 2022
4.  **Title:** "2022 Spring Academic Conference of the Korean Society of Medical Devices and Assistive Technology"
    -   **Conference:** Korean Society of Medical Devices and Assistive Technology
    -   **Date:** May 28, 2022
5.  **Title:** "The 1st Hands-on Workshop of the Korean Society of Neuromusculoskeletal Ultrasonography 2022"
    -   **Conference:** Korean Society of Neuromusculoskeletal Ultrasonography
    -   **Date:** April 30, 2022
6.  **Title:** "2022 Spring Academic Conference of the Korean Society of Clinical Pain Medicine"
    -   **Conference:** Korean Society of Clinical Pain Medicine
    -   **Date:** March 26, 2022
7.  **Title:** "The 2nd Hands-on Workshop of the Korean Society of Neuromusculoskeletal Ultrasonography 2021"
    -   **Conference:** Korean Society of Neuromusculoskeletal Ultrasonography
    -   **Date:** January 15, 2022

### \~ 2021

8.  **Title:** "2021 Online Review Course of the Korean Society of Clinical Pain Medicine"
    -   **Conference:** Korean Society of Clinical Pain Medicine
    -   **Date:** December 4, 2021
9.  **Title:** "2021 Spring Academic Conference of the Korean Society of Clinical Pain Medicine"
    -   **Conference:** Korean Society of Clinical Pain Medicine
    -   **Date:** March 27, 2021
10. **Title:** "2020 Online Review Course of the Korean Society of Clinical Pain Medicine"
    -   **Conference:** Korean Society of Clinical Pain Medicine
    -   **Date:** December 5, 2020
11. **Title:** "2020 Autumn Academic Conference of the Korean Society of Clinical Pain Medicine"
    -   **Conference:** Korean Society of Clinical Pain Medicine
    -   **Date:** November 14, 2020

## Professional Memberships

-   Korean Medical Association
    -   Member (2010-present)
    -   Central Director (2017-2018)
    -   Representative Assembly (2017-2018)
-   Korean Association of Public Health Doctors
    -   Member (2015-2018)
    -   Vice President (2017-2018)
    -   Advisor (2018-2019)
-   Korean Academy of Rehabilitation Medicine
    -   Member (2011-present)
    -   Clinical Practice Guideline Committee Member (2022-2024)
-   Korean Society of Pain Medicine
    -   Member (2018-present)
    -   Academic Committee Member (2019-present)
-   Korean Society of Sports Medicine
    -   Member (2018-present)
-   Korean Academy of Neuro-Musculoskeletal Sonography
    -   Member (2018-present)
    -   Education Committee Member (2022-present)
-   Korean Society of Artificial Intelligence in Medicine
    -   Member (2019-present)
-   The Korean Pain Research Society
    -   Member (2022-present)
    -   Planning Committee Member (2022-present)
-   International Society of Physical & Rehabilitation Medicine
    -   Member (2022-present)

## Reviewer

-   Annals of Rehabilitation Medicine

## Teaching

-   Course: Student Internship Program in Rehabilitation Medicine
    -   Academic Year: 2022-2023
    -   Institution: Kosin University College of Medicine
    -   Role: Supervising Professor
-   Course: Clinical Practicum in Rehabilitation Medicine
    -   Academic Year: 2020-2023
    -   Institution: Kosin University College of Medicine
    -   Role: Course Coordinator(2022-) and Lecturer
-   Course: CPX Internal Special Lecture
    -   Academic Year: 2020-2023
    -   Institution: Kosin University College of Medicine
    -   Role: Evaluator and Lecturer
-   Course: Respiratory Medicine
    -   title: Pulmonary rehabilitation
    -   Academic Year: 2020-2023
    -   Institution: Kosin University College of Medicine
    -   Role: Lecturer
-   Course: Neuroscience
    -   title: Pain & pain pathway
    -   Academic Year: 2020-2023
    -   Institution: Kosin University College of Medicine
    -   Role: Lecturer
-   Course: Growth and Aging
    -   title: Geriatric Musculoskeletal Disorders
    -   Academic Year: 2020-2022
    -   Institution: Kosin University College of Medicine
    -   Role: Lecturer
-   Course: Medical Informatics in rehabilitative medicine
    -   title: Medical Informatics
    -   Academic Year: 2020-2022
    -   Institution: Kosin University College of Medicine
    -   Role: Lecturer

## AWARDS
1. **title**: "Pressure Characteristics of the Knee Joints"
-   **conference**: 2019 대한신경근골격초음파학회춘계학술대회
-   **AWARD**: Best oral presentation

## Media

1.  **Title:** 부산mbc라디오 '생방송 오늘 저녁, 부산입니다.'
-   **Date:** November 2, 2021
1.  **Title:** 'KNN 웰빙라이프'
-   **Date:** October 12-17, 2020
