project:
  type: website
  output-dir: docs

website:
  title: "Jaehyun Lee, MD"
  navbar:
    brand:
      href: index.qmd
    left:
      - text: Publications & Grants
        href: 01publications.qmd
      - text: Academic Activities
        href: 02activities.qmd
      - text: Album
        href: 03album.qmd
      - 04blog.qmd
    right:
      - icon: person-lines-fill
        text: Curriculum Vitae
        href: about.qmd
      - icon: box-arrow-up-right
        text: Digital Garden
        href: https://msk8rehab.vercel.app/
    toc:
      before: |
        <nav class="toc">
          <h2>Table of Contents</h2>
          <ul>
      after: |
          </ul>
          </nav>
        
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    number_sections: true
    theme:
      name: readable
      primary_color: "#2980b9"
      secondary_color: "#3498db"
      font: Arial, sans-serif

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

script:
  head: |
    <style>
      /* 스타일링을 위한 CSS 스타일 시트 */

      /* 예시: 네비게이션 바 배경색 변경 */
      .navbar {
        background-color: #f8f9fa;
      }

      /* 예시: 목차 스타일 변경 */
      .toc {
        background-color: #f1f1f1;
        padding: 10px;
      }

      .toc h2 {
        color: #333;
      }

      .toc ul {
        list-style-type: none;
        padding-left: 0;
      }

      .toc ul li {
        margin-bottom: 5px;
      }
    </style>
